[package]
name = "javardry-spoiler-web"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.45"
gloo-file = { version = "0.2.0", features = ["futures"] }
itertools = "0.10.1"
javardry-spoiler = { path = "javardry-spoiler" }
seed = "0.8.0"
