[package]
name = "javardry-spoiler"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.45"
bitflags = "1.3.2"
block-modes = "0.8.1"
des = "0.7.0"
env_logger = "0.9.0"
log = "0.4.14"
md-5 = "0.9.1"
num_enum = "0.5.4"
once_cell = "1.8.0"
regex = "1.5.4"
structopt = "0.3.25"
